#!/usr/bin/env node
// Generates the core<->shell contract for BOTH languages from one schema.
// Hand-writing either side is how the two drift at the same protocol version.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const s = JSON.parse(readFileSync(join(here, 'schema/protocol.json'), 'utf8'));
const banner = (c) => `${c} GENERATED by protocol/generate.mjs from protocol/schema/protocol.json\n${c} Do not edit. Run \`npm run gen\`.\n`;
const pascal = (n) => n.split(/[._]/).map(p => p[0].toUpperCase() + p.slice(1)).join('');

// ---------- TypeScript ----------
const ts = [
  banner('//'),
  `export const PROTOCOL_VERSION = ${s.version};\n`,
  declaredTypes(),
  `export type ErrorCode =\n${s.errors.map(e => `  | ${JSON.stringify(e)}`).join('\n')};\n`,
  `export type CommandName =\n${s.commands.map(c => `  | ${JSON.stringify(c.name)}`).join('\n')};\n`,
  `export interface CommandArgs {`,
  // A command with no arguments must be Record<string, never>, not `{}` — a bare empty
  // object type accepts 0 and "" and would let a malformed call through the contract.
  ...s.commands.map(c => {
    const keys = Object.entries(c.args);
    const body = keys.length
      ? `{ ${keys.map(([k, v]) => `${k}: ${tsType(v)}`).join('; ')} }`
      : 'Record<string, never>';
    return `  ${JSON.stringify(c.name)}: ${body};`;
  }),
  `}\n`,
  `export interface CommandResult {`,
  ...s.commands.map(c => `  ${JSON.stringify(c.name)}: ${c.returns};`),
  `}\n`,
  `export type Topic = ${Object.keys(s.topics).map(t => JSON.stringify(t)).join(' | ')};\n`,
  `export interface TopicEvents {`,
  ...Object.entries(s.topics).map(([t, evs]) => `  ${JSON.stringify(t)}: ${evs.map(e => JSON.stringify(e)).join(' | ')};`),
  `}\n`,
  `/** The renderer never originates a path or an executable; these carry shell-issued capability values. */`,
  `export const PRIVILEGED_COMMANDS = [${s.commands.filter(c => c.privileged).map(c => JSON.stringify(c.name)).join(', ')}] as const;\n`,
].join('\n');


// Every non-primitive named in the schema gets a declaration, so the generated file is
// self-contained and `tsc --noEmit` is a real gate. Payload shapes are `unknown` until the
// command is implemented: that forces a narrowing at the call site instead of permitting a
// silent `any`. Identifiers are branded so a ProjectId cannot be passed where a SessionId goes.
function declaredTypes() {
  const prim = new Set(['u32', 'bool', 'String']);
  const names = new Set();
  for (const c of s.commands) {
    for (const t of Object.values(c.args)) if (!prim.has(t)) names.add(t);
    if (!prim.has(c.returns)) names.add(c.returns);
  }
  const out = [];
  for (const n of [...names].sort()) {
    if (n === 'Empty') out.push(`export type Empty = Record<string, never>;`);
    else if (n === 'Url') out.push(`export type Url = string;`);
    else if (n.endsWith('Id') || n.endsWith('Ref') || n === 'OsPath')
      out.push(`export type ${n} = string & { readonly __brand: '${n}' };`);
    else if (n === 'Sort')
      out.push(`export type Sort = 'lastTouched' | 'completion' | 'name' | 'size' | 'age';`);
    else out.push(`/** Shape lands with the command's implementation. */\nexport type ${n} = unknown;`);
  }
  return out.join('\n') + '\n';
}

function tsType(t) {
  switch (t) {
    case 'u32': return 'number'; case 'bool': return 'boolean'; case 'String': return 'string';
    default: return t; // opaque branded types are declared in app/src/types.ts
  }
}

// ---------- Rust ----------
const rs = [
  banner('//'),
  `// Generated bindings precede their consumers: commands are added to the schema before the`,
  `// core implements them, so unused variants are expected and are not a defect.`,
  `#![allow(dead_code)]\n`,
  `pub const PROTOCOL_VERSION: u32 = ${s.version};\n`,
  `#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]`,
  `#[serde(rename_all = "SCREAMING_SNAKE_CASE")]`,
  `pub enum ErrorCode {`,
  ...s.errors.map(e => `    ${pascal(e.toLowerCase())},`),
  `}\n`,
  `#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]`,
  `pub enum CommandName {`,
  ...s.commands.map(c => `    #[serde(rename = ${JSON.stringify(c.name)})]\n    ${pascal(c.name)},`),
  `}\n`,
  `#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]`,
  `pub enum Topic {`,
  ...Object.keys(s.topics).map(t => `    #[serde(rename = ${JSON.stringify(t)})]\n    ${pascal(t)},`),
  `}\n`,
].join('\n');

// Bindings are generated INTO each consumer's source tree, so each language's own build
// (tsc rootDir, cargo module resolution) sees them as ordinary local sources.
mkdirSync(join(root, 'app/src/generated'), { recursive: true });
writeFileSync(join(root, 'app/src/generated/protocol.ts'), ts);
writeFileSync(join(root, 'core/src/protocol.rs'), rs);
console.log(`protocol v${s.version}: ${s.commands.length} commands, ${Object.keys(s.topics).length} topics -> app/src/generated + core/src`);
