// Schema -> core/src/protocol.rs. Pure; writes nothing.
import { SCALARS, parseTypeExpr } from './schema.mjs';
import { pascal } from './emit-ts.mjs';

const BANNER =
  '// GENERATED by protocol/generate.mjs from protocol/schema/protocol.json\n' +
  '// Do not edit. Run `npm run gen`.\n';

const KEYWORDS = new Set([
  'as',
  'async',
  'await',
  'box',
  'break',
  'const',
  'continue',
  'crate',
  'do',
  'dyn',
  'else',
  'enum',
  'extern',
  'false',
  'final',
  'fn',
  'for',
  'if',
  'impl',
  'in',
  'let',
  'loop',
  'macro',
  'match',
  'mod',
  'move',
  'mut',
  'override',
  'priv',
  'pub',
  'ref',
  'return',
  'self',
  'static',
  'struct',
  'super',
  'trait',
  'true',
  'try',
  'type',
  'typeof',
  'union',
  'unsafe',
  'unsized',
  'use',
  'virtual',
  'where',
  'while',
  'yield',
]);

function snake(name) {
  const s = name.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);
  return KEYWORDS.has(s) ? `r#${s}` : s;
}

const DERIVE_DATA = '#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]';
const DERIVE_UNIT =
  '#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]';
const DERIVE_TEXT_ID =
  '#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]';

function rsRef(expr) {
  const { base, array, nullable } = parseTypeExpr(expr);
  const leaf = SCALARS[base] ? SCALARS[base].rs : base;
  const body = array ? `Vec<${leaf}>` : leaf;
  return nullable ? `Option<${body}>` : body;
}

/**
 * `pub enum Name { … }`, collapsed to `{}` when there are no variants. rustfmt rejects a brace
 * pair with a blank line between, and an empty topic or command set is a real schema state.
 */
function enumOf(derive, name, variantLines, attrs = '') {
  const head = `${derive}\n${attrs}pub enum ${name}`;
  return variantLines.length === 0 ? `${head} {}\n` : `${head} {\n${variantLines.join('\n')}\n}\n`;
}

function structOf(name, fields) {
  const body = Object.entries(fields)
    .map(([f, e]) => `    pub ${snake(f)}: ${rsRef(e)},`)
    .join('\n');
  return `${DERIVE_DATA}\n#[serde(rename_all = "camelCase", deny_unknown_fields)]\npub struct ${name} {${
    body ? `\n${body}\n` : ''
  }}\n`;
}

export function emitRust(schema) {
  const L = [];
  L.push(BANNER);
  L.push('// Bindings precede their consumers: a command is added to the schema before the core');
  L.push('// implements it, so unused variants are expected and are not a defect. The allows are');
  L.push('// shape complaints about generated data types, not about the code that uses them.');
  // Laid out the way rustfmt lays it out: this file is checked by `cargo fmt --check` like any
  // other, so the emitter has to produce canonical text rather than merely valid text.
  L.push(`#![allow(
    dead_code,
    clippy::large_enum_variant,
    clippy::struct_excessive_bools,
    clippy::struct_field_names,
    clippy::doc_markdown,
    clippy::module_name_repetitions
)]
`);
  L.push(`pub const PROTOCOL_VERSION: u32 = ${schema.version};\n`);

  // §2.5: bytes cross tagged. A Vec<u8> would round-trip as a JSON array, which is not the form
  // the shell and the renderer are specified to read.
  L.push(`#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Bytes(pub Vec<u8>);

#[derive(serde::Serialize, serde::Deserialize)]
struct BytesWire {
    // Pinned rather than inherited from the field name: this single key is the whole of §2.5's
    // tagging, and it must not move if this struct ever gains a rename_all.
    #[serde(rename = "b64")]
    b64: String,
}

impl serde::Serialize for Bytes {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use base64::Engine as _;
        BytesWire {
            b64: base64::engine::general_purpose::STANDARD.encode(&self.0),
        }
        .serialize(s)
    }
}

impl<'de> serde::Deserialize<'de> for Bytes {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use base64::Engine as _;
        use serde::de::Error as _;
        let w = BytesWire::deserialize(d)?;
        base64::engine::general_purpose::STANDARD
            .decode(w.b64.as_bytes())
            .map(Bytes)
            .map_err(D::Error::custom)
    }
}
`);

  for (const name of Object.keys(schema.types).sort()) {
    const decl = schema.types[name];
    if (decl.kind === 'id') {
      const i64 = decl.repr === 'i64';
      L.push(
        `${i64 ? DERIVE_UNIT : DERIVE_TEXT_ID}\n#[serde(transparent)]\npub struct ${name}(pub ${
          i64 ? 'i64' : 'String'
        });\n`,
      );
    } else if (decl.kind === 'enum') {
      const variants = decl.variants
        .map((v) => `    #[serde(rename = "${v}")]\n    ${pascal(v)},`)
        .join('\n');
      L.push(`${DERIVE_UNIT}\npub enum ${name} {\n${variants}\n}\n`);
      // [p3] The runtime variant list, **derived by construction**. The project's convention for
      // "every kind, so a test can walk the vocabulary without restating it" was a hand-written
      // `ALL` on core-side enums only, and a generated enum had none — so a consumer that needed
      // one at run time had to write the count down, which is the hand-maintained count R132/F11
      // rules against. Emitting it for every enum removes that for all of them at once.
      const paths = decl.variants.map((v) => `${name}::${pascal(v)}`);
      const head = `    pub const ALL: [${name}; ${decl.variants.length}] = `;
      // rustfmt collapses a short array onto one line and explodes a long one, and `gen:check`
      // compares the emitted text with what `cargo fmt` leaves behind — so the emitter has to
      // pick the same form rather than leave the file one `cargo fmt` away from out of date.
      const oneLine = `${head}[${paths.join(', ')}];`;
      const body =
        oneLine.length <= 100
          ? oneLine
          : `${head}[\n${paths.map((p) => `        ${p},`).join('\n')}\n    ];`;
      L.push(
        `impl ${name} {\n` +
          `    /// Every variant the schema declares, in declaration order.\n` +
          `${body}\n}\n`,
      );
    } else {
      L.push(structOf(name, decl.fields));
    }
  }

  const errVariants = schema.errors
    .map((e) => `    #[serde(rename = "${e}")]\n    ${pascal(e.toLowerCase())},`)
    .join('\n');
  L.push(`${DERIVE_UNIT}\npub enum ErrorCode {\n${errVariants}\n}\n`);

  for (const c of schema.commands) L.push(structOf(`${pascal(c.name)}Args`, c.args));

  L.push(
    enumOf(
      DERIVE_UNIT,
      'CommandName',
      schema.commands.map((c) => `    #[serde(rename = "${c.name}")]\n    ${pascal(c.name)},`),
    ),
  );

  L.push(
    enumOf(
      DERIVE_DATA,
      'Command',
      schema.commands.map(
        (c) => `    #[serde(rename = "${c.name}")]\n    ${pascal(c.name)}(${pascal(c.name)}Args),`,
      ),
      '#[serde(tag = "command", content = "args")]\n',
    ),
  );

  // Untagged and serialize-only: the response frame carries the request id, so repeating the
  // command name inside the payload would be a second source of truth. The renderer narrows on
  // its own CommandResult map instead.
  const resArms = schema.commands
    .map((c) => `    ${pascal(c.name)}(${rsRef(c.returns)}),`)
    .join('\n');
  const resName = schema.commands
    .map((c) => `            Self::${pascal(c.name)}(_) => CommandName::${pascal(c.name)},`)
    .join('\n');
  L.push(`#[derive(Debug, Clone, PartialEq, serde::Serialize)]
#[serde(untagged)]
pub enum CommandResultValue {
${resArms}
}

impl CommandResultValue {
    #[must_use]
    pub fn command(&self) -> CommandName {
        match self {
${resName}
        }
    }
}
`);

  const topics = Object.keys(schema.topics);
  L.push(
    enumOf(
      DERIVE_UNIT,
      'Topic',
      topics.map((t) => `    #[serde(rename = "${t}")]\n    ${pascal(t)},`),
    ),
  );

  for (const t of topics) {
    const evs = Object.entries(schema.topics[t]);
    const arms = evs.map(([e, expr]) => `    ${pascal(e)}(${rsRef(expr)}),`).join('\n');
    const names = evs.map(([e]) => `            Self::${pascal(e)}(_) => "${e}",`).join('\n');
    L.push(`#[derive(Debug, Clone, PartialEq, serde::Serialize)]
#[serde(untagged)]
pub enum ${pascal(t)}Event {
${arms}
}

impl ${pascal(t)}Event {
    #[must_use]
    pub fn name(&self) -> &'static str {
        match self {
${names}
        }
    }

    #[must_use]
    pub fn topic(&self) -> Topic {
        Topic::${pascal(t)}
    }
}
`);
  }

  return L.join('\n');
}
