// Schema -> app/src/generated/protocol.ts. Pure; writes nothing.
// Strictness rules honoured here so consumers never fight the compiler:
//   * no optional properties  -> exactOptionalPropertyTypes is a non-event
//   * readonly arrays         -> noUncheckedIndexedAccess forces a narrow at the use site
//   * no index signatures     -> noPropertyAccessFromIndexSignature is a non-event
//   * no `any`, every helper annotated -> the app's eslint rules pass on generated text
import { SCALARS, parseTypeExpr } from './schema.mjs';

const BANNER =
  '// GENERATED by protocol/generate.mjs from protocol/schema/protocol.json\n' +
  '// Do not edit. Run `npm run gen`.\n';

export const pascal = (n) =>
  n
    .split(/[._/]/)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join('');

function tsRef(expr) {
  const { base, array, nullable } = parseTypeExpr(expr);
  const leaf = SCALARS[base] ? SCALARS[base].ts : base;
  const body = array ? `readonly ${leaf}[]` : leaf;
  return nullable ? `${body} | null` : body;
}

function declare(name, fields) {
  const entries = Object.entries(fields);
  if (entries.length === 0) return `export type ${name} = Record<string, never>;`;
  const body = entries.map(([f, e]) => `  readonly ${f}: ${tsRef(e)};`).join('\n');
  return `export interface ${name} {\n${body}\n}`;
}

export function emitTypeScript(schema) {
  const L = [];
  L.push(BANNER);
  L.push(`export const PROTOCOL_VERSION = ${schema.version};\n`);

  L.push('/** §2.5: where raw bytes must cross the wire they are tagged, never stringified. */');
  L.push('export interface Bytes {\n  readonly b64: string;\n}\n');

  for (const name of Object.keys(schema.types).sort()) {
    const decl = schema.types[name];
    if (decl.kind === 'id') {
      const prim = decl.repr === 'i64' ? 'number' : 'string';
      L.push(`export type ${name} = ${prim} & { readonly __brand: '${name}' };`);
    } else if (decl.kind === 'enum') {
      L.push(`export type ${name} = ${decl.variants.map((v) => `'${v}'`).join(' | ')};`);
    } else {
      L.push(declare(name, decl.fields));
    }
  }
  L.push('');

  L.push(`export type ErrorCode =\n${schema.errors.map((e) => `  | '${e}'`).join('\n')};\n`);
  L.push(
    `export const ERROR_CODES: readonly ErrorCode[] = [${schema.errors
      .map((e) => `'${e}'`)
      .join(', ')}];\n`,
  );

  for (const c of schema.commands) L.push(declare(`${pascal(c.name)}Args`, c.args));
  L.push('');

  L.push(
    `export type CommandName =\n${schema.commands.map((c) => `  | '${c.name}'`).join('\n')};\n`,
  );
  L.push('export interface CommandArgs {');
  for (const c of schema.commands) L.push(`  '${c.name}': ${pascal(c.name)}Args;`);
  L.push('}\n');
  L.push('export interface CommandResult {');
  for (const c of schema.commands) L.push(`  '${c.name}': ${tsRef(c.returns)};`);
  L.push('}\n');

  const topics = Object.keys(schema.topics);
  L.push(`export type Topic = ${topics.map((t) => `'${t}'`).join(' | ')};\n`);
  L.push('export interface TopicEvents {');
  for (const t of topics) {
    L.push(
      `  '${t}': ${Object.keys(schema.topics[t])
        .map((e) => `'${e}'`)
        .join(' | ')};`,
    );
  }
  L.push('}\n');
  L.push('/** Keyed `topic/event`, so a handler narrows on one string. */');
  L.push('export interface EventPayloads {');
  for (const t of topics) {
    for (const [e, expr] of Object.entries(schema.topics[t])) {
      L.push(`  '${t}/${e}': ${tsRef(expr)};`);
    }
  }
  L.push('}\n');

  const priv = schema.commands.filter((c) => c.privileged === true).map((c) => `'${c.name}'`);
  L.push('/** §2.4: these carry a value issued by a shell-owned native dialog. The renderer may');
  L.push(' *  never originate a filesystem path or an executable, so it may never call one. */');
  L.push(`export const PRIVILEGED_COMMANDS = [${priv.join(', ')}] as const;\n`);

  const nonIdem = schema.commands.filter((c) => c.idempotent === false).map((c) => `'${c.name}'`);
  L.push(
    '/** §2.2: on core death these are rejected `{code: "CORE_RESTARTED", outcome: "unknown"}`',
  );
  L.push(' *  and are never auto-replayed — replaying a launch opens the editor twice. */');
  L.push(`export const NON_IDEMPOTENT_COMMANDS = [${nonIdem.join(', ')}] as const;\n`);

  return L.join('\n');
}
